// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vizsgaController.Persistence;

#nullable disable

namespace vizsgaController.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20260220111143_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostUser", b =>
                {
                    b.Property<int>("FavouritesPostID")
                        .HasColumnType("integer");

                    b.Property<int>("User1UserID")
                        .HasColumnType("integer");

                    b.HasKey("FavouritesPostID", "User1UserID");

                    b.HasIndex("User1UserID");

                    b.ToTable("UserFavourites", (string)null);
                });

            modelBuilder.Entity("PostUser1", b =>
                {
                    b.Property<int>("Upvoted_PostsPostID")
                        .HasColumnType("integer");

                    b.Property<int>("User2UserID")
                        .HasColumnType("integer");

                    b.HasKey("Upvoted_PostsPostID", "User2UserID");

                    b.HasIndex("User2UserID");

                    b.ToTable("UserUpvotes", (string)null);
                });

            modelBuilder.Entity("PostUser2", b =>
                {
                    b.Property<int>("Downvoted_PostsPostID")
                        .HasColumnType("integer");

                    b.Property<int>("User3UserID")
                        .HasColumnType("integer");

                    b.HasKey("Downvoted_PostsPostID", "User3UserID");

                    b.HasIndex("User3UserID");

                    b.ToTable("UserDownvotes", (string)null);
                });

            modelBuilder.Entity("vizsgaController.Persistence.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryID");

                    b.HasIndex("Categoryname")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("vizsgaController.Persistence.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentID"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CommentCreated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostID")
                        .HasColumnType("integer");

                    b.HasKey("CommentID");

                    b.HasIndex("PostID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("vizsgaController.Persistence.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("ImageId");

                    b.HasIndex("PostId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("vizsgaController.Persistence.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("PostID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("vizsgaController.Persistence.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportID"));

                    b.Property<int>("PostID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportCreated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ReportID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("vizsgaController.Persistence.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Useremail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Userpassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("Username", "Useremail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.HasOne("vizsgaController.Persistence.Post", null)
                        .WithMany()
                        .HasForeignKey("FavouritesPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vizsgaController.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("User1UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostUser1", b =>
                {
                    b.HasOne("vizsgaController.Persistence.Post", null)
                        .WithMany()
                        .HasForeignKey("Upvoted_PostsPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vizsgaController.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("User2UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostUser2", b =>
                {
                    b.HasOne("vizsgaController.Persistence.Post", null)
                        .WithMany()
                        .HasForeignKey("Downvoted_PostsPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vizsgaController.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("User3UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vizsgaController.Persistence.Comment", b =>
                {
                    b.HasOne("vizsgaController.Persistence.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vizsgaController.Persistence.Image", b =>
                {
                    b.HasOne("vizsgaController.Persistence.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("vizsgaController.Persistence.Post", b =>
                {
                    b.HasOne("vizsgaController.Persistence.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("vizsgaController.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vizsgaController.Persistence.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
